### ISSUE TITLE
Question : Scheduler ?

### ISSUE THREAD

**Issue by tboulogne** [morlandi/django-task#2]
Hello,

I see you'e working hard on this. Greatings !!!
Do you plan a scheduler as django-q did ?

I'm currently using django-q. Could discuss on this.

regards,

Thierry

**Comment by tboulogne** [comment]
UP: 

Find this : https://github.com/istrategylabs/django-rq-scheduler
I will give it a try with django-task.

Regards

**Comment by morlandi** [comment]
Hello @tboulogne .. to be honest I'm just doing some cleanup at the moment, and a revamping of the example project which had been left unattended for too much time ;)
The only real new functionality I'ld like to add would be the possibility to revoke an already running job, but up to now I couldn't find a clear way in django-rq or RQ to achieve this.

I know "django-rq-scheduler", and did some test some time ago when I was comparing RQ with Huey. I remember that occasionally it lost some scheduled jobs, with no apparent reasons, and no clue in the logs; that puzzled me until I read these interesting slides by David Gouldin:

https://speakerdeck.com/dgouldin/using-celery-with-social-networks?slide=57

Check slides n. 57 and 58.
Briefly, he suggests to use cron instead of celerybeat.
That seems reasonable, and that's what I do !

In django-task I provide a base TaskCommand class which makes trivial to create a Django management command to run a Task, the invoke it via cron.
I'm already using cron for several cleanup activities on the server, so I really feel no need to use another specific Django app for this.

I'ld be more than happy to hear your opinions on this issue.

**Comment by tboulogne** [comment]
You ask directly the second question i got for you : killing a running job :-). Let me know if you find something. I dit into this a little and did not find interesting things.

Regarding scheduler, The goal  is to get an admin interface. (i'd like to let customers self handling) I know there is something for cron management into django. Could git it a try :-).

**Comment by morlandi** [comment]
> You ask directly the second question i got for you : killing a running job :-). Let me know if you find something. I dit into this a little and did not find interesting things.

Sure I will

> Regarding scheduler, The goal is to get an admin interface. (i'd like to let customers self handling) I know there is something for cron management into django. Could git it a try :-).

mhhhh ... I see ... For a similar need, I once used django-cron. It provides an admin interface to plan and check scheduled activities, which are not necessarily related to the task queue: these activities might be either background processes or not

**Comment by morlandi** [comment]
@tboulogne I'm closing this issue as no actions are required on the project ... 
Thank you for your interest, and feel free to contact me anytime here.
For any question or suggestion, please open a new issue so other interested people may follow the discussion.
Ciao, Mario
